lista = [8, -2, 's', 3.1, 8, "Ana are mere", None, [1, 2, 3, [4, 5, 6]]]
print(lista[7][3][1])
# print(lista.index(8))
# print(lista[3])
# print(len(lista))
# print(lista[7])
# print(lista[-1])
# print(lista[7:8])
# print(lista[3:])
# print(lista[:4])
# print(lista[0:7:3])
# lista.append(5)
# lista.insert(2, 6)
# lista[3] = 7
# lista.clear()
# print(lista)
# print(type(lista))
